### ISSUE TITLE
Please Update Version Number

### ISSUE THREAD

**Issue by JayBusch** [cbbrowne/pg.el#2]
In an attempt to get PostgresSQL working with EMACS I came across this script published both here on your GitHub page and here: http://www.online-marketwatch.com/pgel/pg.el (among probably other places).  Both files list version 0.12, but a diff shows that they are not identical, and I believe your file is more recent.  For the sake of clarity please update this to 0.13 or something of your choosing to indicate a change in the code, it will really help users trying to get PGSQL functionality in EMACS going.

Of course, thanks much for providing this.

**Comment by cbbrowne** [comment]
I have put in "0.13 (sorta)", and put a tag onto the latest version.

Hope that's helpful!

**Comment by JayBusch** [comment]
Absolutely, and thanks for addressing this!
