### ISSUE TITLE
pg.el is not working with PostgreSQL version 10.1, that dropped protocol 1.0

### ISSUE THREAD

**Issue by gnusupport** [cbbrowne/pg.el#3]
The PostgreSQL version 10.1 is the newest version. It dropped the support for protocol 1.0 which is not in use for many years, and pg.el is still using same protocol.

With the new update, many new GNU/Linux distributions will start submitting reports eventually on pg.el as other packages depend on it.

Please try to see how it may be updated to protocol 2.0 or 3.0

**Comment by emarsden** [comment]
Please see the updated version of pg.el which is now maintained (by the original author) at 

    https://github.com/emarsden/pg-el

It now supports version 3 of the PostgreSQL wire protocol, up to date authentication methods (SCRAM-SHA-256) and TLS connections.

**Comment by gnusupport** [comment]
Thanks
